FROM andrius/crystal-lang as builder

# FROM alpine:latest as builder
# RUN apk add -u crystal shards libc-dev

WORKDIR /src
COPY . .

# RUN shards build --production --static
RUN shards build --production
RUN crystal build --release --no-debug ./src/queue_operation.cr -o ./bin/queue_operation
RUN ldd ./bin/queue_operation | tr -s '[:blank:]' '\n' | grep '^/' | \
    xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'
RUN find ./deps/

#########################################################

FROM alpine
# # In case if there will be issues with DNS again, return to the
# # busybox and uncoment related code about redis and amqp in service_manager.cr
# FROM scratch
# FROM busybox

RUN apk update \
 && apk add curl \
            bash \
 && rm -rf /var/cache/apk/* \
           /tmp/* \
           /var/tmp/*

ENV AMQP_URL     amqp://guest:guest@rabbitmq:5672
ENV REDIS_URL    redis://redis:6379
ENV SERVICE_NAME unic.service.asterisk.queue-operation
ENV MLP_QUEUE    unic.service.mlp

# dependences
COPY --from=builder /src/deps /
# that will fix DNS resolve issue in docker
COPY --from=builder /lib/x86_64-linux-gnu/libnss_dns.so.* /lib/x86_64-linux-gnu/
COPY --from=builder /lib/x86_64-linux-gnu/libresolv.so.*  /lib/x86_64-linux-gnu/
COPY --from=builder /src/bin/queue_operation /queue_operation

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/queue_operation"]
