#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Asterisk < Resource
      # Effective user/group id
      struct SetId
        include JSON::Serializable

        @[JSON::Field(ignore: true)]
        property client : ARI? = nil

        # Effective user id.
        property user : String

        # Effective group id.
        property group : String
      end
    end
  end
end
