#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.1.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Asterisk < Resources
      # Asterisk system information
      struct AsteriskInfo
        include JSON::Serializable

        # Info about how Asterisk was built
        property build : Asterisk::BuildInfo? = nil

        # Info about the system running Asterisk
        property system : Asterisk::SystemInfo? = nil

        # Info about Asterisk configuration
        property config : Asterisk::ConfigInfo? = nil

        # Info about Asterisk status
        property status : StatusInfo? = nil
      end
    end
  end
end
