#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Asterisk < Resources
      # Asterisk ping information
      struct AsteriskPing
        include JSON::Serializable

        # Asterisk id info
        property asterisk_id : String

        # Always string value is pong
        property ping : String

        # The timestamp string of request received time
        property timestamp : String
      end
    end
  end
end
