# ------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
# ------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Bridges < Resources
      # The merging of media from one or more channels.
      #
      # Everyone on the bridge receives the same audio.
      struct Bridge
        include JSON::Serializable

        # Unique identifier for this bridge
        property id : String

        # Name of the current bridging technology
        property technology : String

        # Type of bridge technology
        property bridge_type : String

        # Bridging class
        property bridge_class : String

        # Entity that created the bridge
        property creator : String

        # Name the creator gave the bridge
        property name : String

        # Ids of channels participating in this bridge
        property channels : Array(String)

        # The video mode the bridge is using. One of 'none', 'talker', or 'single'.
        property video_mode : String? = nil

        # The ID of the channel that is the source of video in this bridge, if one exists.
        property video_source_id : String? = nil

        # Timestamp when bridge was created
        property creationtime : Time
      end
    end
  end
end
