#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Channels < Resources
      # Dialplan location (context/extension/priority)
      struct DialplanCEP
        include JSON::Serializable

        # Context in the dialplan
        property context : String

        # Extension in the dialplan
        property exten : String

        # Priority in the dialplan
        property priority : Int64

        # Name of current dialplan application
        property app_name : String

        # Parameter of current dialplan application
        property app_data : String
      end
    end
  end
end
