#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Channels < Resource
      # A specific communication connection between Asterisk and an Endpoint.
      struct Channel
        include JSON::Serializable

        @[JSON::Field(ignore: true)]
        property client : ARI? = nil

        # Unique identifier of the channel.
        #
        # This is the same as the Uniqueid field in AMI.
        property id : String

        # Name of the channel (i.e. SIP/foo-0000a7e3)
        property name : String

        property state : String

        property caller : Channels::CallerID

        property connected : Channels::CallerID

        property accountcode : String

        # Current location in the dialplan
        property dialplan : Channels::DialplanCEP

        # Timestamp when channel was created
        property creationtime : Time

        # The default spoken language
        property language : String

        # Channel variables
        property channelvars : Hash(String, String | Bool | Int32 | Float32)? = nil
      end
    end
  end
end
