#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Endpoints < Resources
      # An external device that may offer/accept calls to/from Asterisk.
#
# Unlike most resources, which have a single unique identifier, an endpoint is uniquely identified by the technology/resource pair.
      struct Endpoint
        include JSON::Serializable

        # Technology of the endpoint
        property technology : String

        # Identifier of the endpoint, specific to the given technology.
        property resource : String

        # Endpoint's state
        property state : String? = nil

        # Id's of channels associated with this endpoint
        property channel_ids : Array(String)
      end
    end
  end
end
