#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Playbacks < Resources
      # Object representing the playback of media to a channel
      struct Playback
        include JSON::Serializable

        # ID for this playback operation
        property id : String

        # The URI for the media currently being played back.
        property media_uri : String

        # If a list of URIs is being played, the next media URI to be played back.
        property next_media_uri : String? = nil

        # URI for the channel or bridge to play the media on
        property target_uri : String

        # For media types that support multiple languages, the language requested for playback.
        property language : String? = nil

        # Current state of the playback operation.
        property state : String
      end
    end
  end
end
