# ------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
# ------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Recordings < Resources
      # A recording that is in progress
      struct LiveRecording
        include JSON::Serializable

        # Base name for the recording
        property name : String

        # Recording format (wav, gsm, etc.)
        property format : String

        # URI for the channel or bridge being recorded
        property target_uri : String

        property state : String

        # Duration in seconds of the recording
        property duration : Int32? = nil

        # Duration of talking, in seconds, detected in the recording. This is only available if the recording was initiated with a non-zero maxSilenceSeconds.
        property talking_duration : Int32? = nil

        # Duration of silence, in seconds, detected in the recording. This is only available if the recording was initiated with a non-zero maxSilenceSeconds.
        property silence_duration : Int32? = nil

        # Cause for recording failure if failed
        property cause : String? = nil
      end
    end
  end
end
