#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class DeviceStates < Resources
      # List all ARI controlled device states.
      def list : HTTP::Client::Response | Array(DeviceStates::DeviceState)
        format_response ari.get("deviceStates")
      end

      # Retrieve the current state of a device.
      #
      # Arguments:
      # - `device_name` - name of the device. (required);
      def get(device_name : String) : HTTP::Client::Response | DeviceStates::DeviceState
        format_response ari.get("deviceStates/#{device_name}")
      end

      # Change the state of a device controlled by ARI. (Note - implicitly creates the device state).
      #
      # Arguments:
      # - `device_name` - name of the device. (required);
      # - `device_state` - device state value. (required);
      #
      # Error responses:
      # - 404 - Device name is missing
      # - 409 - Uncontrolled device specified
      def update(device_name : String, device_state : String)
        params = HTTP::Params.encode({"deviceState" => device_state})
        ari.put "deviceStates/#{device_name}?" + params
      end

      # Destroy a device-state controlled by ARI.
      #
      # Arguments:
      # - `device_name` - name of the device. (required);
      #
      # Error responses:
      # - 404 - Device name is missing
      # - 409 - Uncontrolled device specified
      def delete(device_name : String)
        ari.delete "deviceStates/#{device_name}"
      end
    end
  end
end
