# ------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
# ------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Mailboxes < Resources
      # List all mailboxes.
      def list : HTTP::Client::Response | Array(Mailboxes::Mailbox)
        format_response ari.get("mailboxes"), Array(Mailboxes::Mailbox)
      end

      # Retrieve the current state of a mailbox.
      #
      # Arguments:
      # - `mailbox_name` - name of the mailbox. (required);
      #
      # Error responses:
      # - 404 - Mailbox not found
      def get(mailbox_name : String) : HTTP::Client::Response | Mailboxes::Mailbox
        format_response ari.get("mailboxes/#{mailbox_name}"), Mailboxes::Mailbox
      end

      # Change the state of a mailbox. (Note - implicitly creates the mailbox).
      #
      # Arguments:
      # - `mailbox_name` - name of the mailbox. (required);
      # - `old_messages` - count of old messages in the mailbox. (required);
      # - `new_messages` - count of new messages in the mailbox. (required);
      #
      # Error responses:
      # - 404 - Mailbox not found
      def update(mailbox_name : String, old_messages : Int32, new_messages : Int32)
        params = HTTP::Params.encode({"oldMessages" => old_messages.to_s})
        params += "&" + HTTP::Params.encode({"newMessages" => new_messages.to_s})
        ari.put "mailboxes/#{mailbox_name}?" + params
      end

      # Destroy a mailbox.
      #
      # Arguments:
      # - `mailbox_name` - name of the mailbox. (required);
      #
      # Error responses:
      # - 404 - Mailbox not found
      def delete(mailbox_name : String)
        ari.delete "mailboxes/#{mailbox_name}"
      end
    end
  end
end
