#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Playbacks < Resources
      # Get a playback's details.
      #
      # Arguments:
      # - `playback_id` - playback's id. (required);
      #
      # Error responses:
      # - 404 - The playback cannot be found
      def get(playback_id : String) : HTTP::Client::Response | Playbacks::Playback
        format_response ari.get("playbacks/#{playback_id}"), Playbacks::Playback
      end

      # Stop a playback.
      #
      # Arguments:
      # - `playback_id` - playback's id. (required);
      #
      # Error responses:
      # - 404 - The playback cannot be found
      def stop(playback_id : String)
        ari.delete "playbacks/#{playback_id}"
      end

      # Control a playback.
      #
      # Arguments:
      # - `playback_id` - playback's id. (required);
      # - `operation` - operation to perform on the playback. (required);
      #
      # Error responses:
      # - 400 - The provided operation parameter was invalid
      # - 404 - The playback cannot be found
      # - 409 - The operation cannot be performed in the playback's current state
      def control(playback_id : String, operation : String)
        params = HTTP::Params.encode({"operation" => operation})
        ari.post "playbacks/#{playback_id}/control?" + params
      end
    end
  end
end
