#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    class Sounds < Resources
      # List all sounds.
      #
      # Arguments:
      # - `lang` - lookup sound for a specific language;
      # - `format` - lookup sound in a specific format;
      def list(lang : String? = nil, format : String? = nil) : HTTP::Client::Response | Array(Sounds::Sound)
        # Optional parameters
        params = HTTP::Params.encode({} of String => String)
        params += "&" + HTTP::Params.encode({"lang" => lang}) if lang
        params += "&" + HTTP::Params.encode({"format" => format}) if format

        request = "sounds?" + params
        format_response ari.get(request)
      end

      # Get a sound's details.
      #
      # Arguments:
      # - `sound_id` - sound's id. (required);
      def get(sound_id : String) : HTTP::Client::Response | Sounds::Sound
        format_response ari.get("sounds/#{sound_id}")
      end
    end
  end
end
