#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.1.
#
#------------------------------------------------------------------------------

module Asterisk
  class ARI
    module Callbacks
      def on_missing_params(&@on_missing_params : ARI, Events::MissingParams ->)
      end

      def on_contact_info(&@on_contact_info : ARI, Events::ContactInfo ->)
      end

      def on_peer(&@on_peer : ARI, Events::Peer ->)
      end

      def on_device_state_changed(&@on_device_state_changed : ARI, Events::DeviceStateChanged ->)
      end

      def on_playback_started(&@on_playback_started : ARI, Events::PlaybackStarted ->)
      end

      def on_playback_continuing(&@on_playback_continuing : ARI, Events::PlaybackContinuing ->)
      end

      def on_playback_finished(&@on_playback_finished : ARI, Events::PlaybackFinished ->)
      end

      def on_recording_started(&@on_recording_started : ARI, Events::RecordingStarted ->)
      end

      def on_recording_finished(&@on_recording_finished : ARI, Events::RecordingFinished ->)
      end

      def on_recording_failed(&@on_recording_failed : ARI, Events::RecordingFailed ->)
      end

      def on_application_move_failed(&@on_application_move_failed : ARI, Events::ApplicationMoveFailed ->)
      end

      def on_application_replaced(&@on_application_replaced : ARI, Events::ApplicationReplaced ->)
      end

      def on_bridge_created(&@on_bridge_created : ARI, Events::BridgeCreated ->)
      end

      def on_bridge_destroyed(&@on_bridge_destroyed : ARI, Events::BridgeDestroyed ->)
      end

      def on_bridge_merged(&@on_bridge_merged : ARI, Events::BridgeMerged ->)
      end

      def on_bridge_video_source_changed(&@on_bridge_video_source_changed : ARI, Events::BridgeVideoSourceChanged ->)
      end

      def on_bridge_blind_transfer(&@on_bridge_blind_transfer : ARI, Events::BridgeBlindTransfer ->)
      end

      def on_bridge_attended_transfer(&@on_bridge_attended_transfer : ARI, Events::BridgeAttendedTransfer ->)
      end

      def on_channel_created(&@on_channel_created : ARI, Events::ChannelCreated ->)
      end

      def on_channel_destroyed(&@on_channel_destroyed : ARI, Events::ChannelDestroyed ->)
      end

      def on_channel_entered_bridge(&@on_channel_entered_bridge : ARI, Events::ChannelEnteredBridge ->)
      end

      def on_channel_left_bridge(&@on_channel_left_bridge : ARI, Events::ChannelLeftBridge ->)
      end

      def on_channel_state_change(&@on_channel_state_change : ARI, Events::ChannelStateChange ->)
      end

      def on_channel_dtmf_received(&@on_channel_dtmf_received : ARI, Events::ChannelDtmfReceived ->)
      end

      def on_channel_dialplan(&@on_channel_dialplan : ARI, Events::ChannelDialplan ->)
      end

      def on_channel_caller_id(&@on_channel_caller_id : ARI, Events::ChannelCallerId ->)
      end

      def on_channel_userevent(&@on_channel_userevent : ARI, Events::ChannelUserevent ->)
      end

      def on_channel_hangup_request(&@on_channel_hangup_request : ARI, Events::ChannelHangupRequest ->)
      end

      def on_channel_varset(&@on_channel_varset : ARI, Events::ChannelVarset ->)
      end

      def on_channel_hold(&@on_channel_hold : ARI, Events::ChannelHold ->)
      end

      def on_channel_unhold(&@on_channel_unhold : ARI, Events::ChannelUnhold ->)
      end

      def on_channel_talking_started(&@on_channel_talking_started : ARI, Events::ChannelTalkingStarted ->)
      end

      def on_channel_talking_finished(&@on_channel_talking_finished : ARI, Events::ChannelTalkingFinished ->)
      end

      def on_contact_status_change(&@on_contact_status_change : ARI, Events::ContactStatusChange ->)
      end

      def on_peer_status_change(&@on_peer_status_change : ARI, Events::PeerStatusChange ->)
      end

      def on_endpoint_state_change(&@on_endpoint_state_change : ARI, Events::EndpointStateChange ->)
      end

      def on_dial(&@on_dial : ARI, Events::Dial ->)
      end

      def on_stasis_end(&@on_stasis_end : ARI, Events::StasisEnd ->)
      end

      def on_stasis_start(&@on_stasis_start : ARI, Events::StasisStart ->)
      end

      def on_text_message_received(&@on_text_message_received : ARI, Events::TextMessageReceived ->)
      end

      def on_channel_connected_line(&@on_channel_connected_line : ARI, Events::ChannelConnectedLine ->)
      end
    end
  end
end
