#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------
require "./event.cr"


module Asterisk
  class ARI
    class Events < Resource
      # Notification that trying to move a channel to another Stasis application failed.
      struct ApplicationMoveFailed < Event

        property channel : Channels::Channel

        property destination : String

        # Arguments to the application
        property args : Array(String)
      end
    end
  end
end
