#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------
require "./event.cr"

module Asterisk
  class ARI
    class Events < Resource
      # User-generated event with additional user-defined fields in the object.
      struct ChannelUserevent < Event

        # The name of the user event.
        property eventname : String

        # A channel that is signaled with the user event.
        property channel : Channels::Channel? = nil

        # A bridge that is signaled with the user event.
        property bridge : Bridges::Bridge? = nil

        # A endpoint that is signaled with the user event.
        property endpoint : Int32? = nil

        # Custom Userevent data
        property userevent : Hash(String, String | Bool | Int32 | Float32)
      end
    end
  end
end
