#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.1.
#
#------------------------------------------------------------------------------
require "./event.cr"

module Asterisk
  class ARI
    class Events < Resources
      # Channel changed Caller ID.
      struct ChannelCallerId < Event

        # The integer representation of the Caller Presentation value.
        property caller_presentation : Int32

        # The text representation of the Caller Presentation value.
        property caller_presentation_txt : String

        # The channel that changed Caller ID.
        property channel : Channels::Channel
      end
    end
  end
end
