#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------
require "./event.cr"


module Asterisk
  class ARI
    class Events < Resource
      # Channel changed location in the dialplan.
      struct ChannelDialplan < Event

        # The channel that changed dialplan location.
        property channel : Channels::Channel

        # The application about to be executed.
        property dialplan_app : String

        # The data to be passed to the application.
        property dialplan_app_data : String
      end
    end
  end
end
