#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.1.
#
#------------------------------------------------------------------------------
require "./event.cr"

module Asterisk
  class ARI
    class Events < Resources
      # Talking is no longer detected on the channel.
      struct ChannelTalkingFinished < Event

        # The channel on which talking completed.
        property channel : Channels::Channel

        # The length of time, in milliseconds, that talking was detected on the channel
        property duration : Int32
      end
    end
  end
end
