#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------
require "./event.cr"

module Asterisk
  class ARI
    class Events < Resources
      # Dialing state has changed.
      struct Dial < Event

        # The calling channel.
        property caller : Channels::Channel? = nil

        # The dialed channel.
        property peer : Channels::Channel

        # Forwarding target requested by the original dialed channel.
        property forward : String? = nil

        # Channel that the caller has been forwarded to.
        property forwarded : Channels::Channel? = nil

        # The dial string for calling the peer channel.
        property dialstring : String? = nil

        # Current status of the dialing attempt to the peer.
        property dialstatus : String
      end
    end
  end
end
