#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.6.0.
#
#------------------------------------------------------------------------------
require "./message.cr"

module Asterisk
  class ARI
    class Events < Resources
      # Error event sent when required params are missing.
      struct MissingParams < Message

        # A list of the missing parameters
        property params : Array(String)
      end
    end
  end
end
