#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------
require "./event.cr"

module Asterisk
  class ARI
    class Events < Resource
      # Detailed information about a remote peer that communicates with Asterisk.
      struct Peer < Event

        # The current state of the peer. Note that the values of the status are dependent on the underlying peer technology.
        property peer_status : String

        # An optional reason associated with the change in peer_status.
        property cause : String? = nil

        # The IP address of the peer.
        property address : String? = nil

        # The port of the peer.
        property port : String? = nil

        # The last known time the peer was contacted.
        property time : String? = nil
      end
    end
  end
end
