#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using ctiapps/asterisk crystal shard from the
#  Asterisk PBX version 16.5.0.
#
#------------------------------------------------------------------------------
require "./event.cr"

module Asterisk
  class ARI
    class Events < Resources
      # Notification that a channel has entered a Stasis application.
      struct StasisStart < Event

        # Arguments to the application
        property args : Array(String)

        property channel : Channels::Channel

        property replace_channel : Channels::Channel? = nil
      end
    end
  end
end
